### ISSUE TITLE
Cannot build with go1.9 for GTK ??

### ISSUE THREAD

**Issue by ZaniaDeveloper** [cztomczak/cef2go#36]
Hello,

I tried to build by following the README.md but i had this output:
```
go install gtk
# gtk
src/gtk/gtk.go: In function ‘TerminationSignal’:
src/gtk/gtk.go:14:39: warning: implicit declaration of function ‘cef_quit_message_loop’ [-Wimplicit-function-declaration]
 void TerminationSignal(int signatl) { cef_quit_message_loop(); }
                                       ^~~~~~~~~~~~~~~~~~~~~
src/gtk/gtk.go: In function ‘DestroySignal’:
src/gtk/gtk.go:20:5: warning: implicit declaration of function ‘_GoDestroySignal’ [-Wimplicit-function-declaration]
     _GoDestroySignal(widget, data);
     ^~~~~~~~~~~~~~~~
go install cef
# cef
In file included from /home/frederic/go/src/github.com/cztomczak/cef2go/include/internal/cef_types.h:46:0,
                 from /home/frederic/go/src/github.com/cztomczak/cef2go/include/capi/cef_base_capi.h:43,
                 from /home/frederic/go/src/github.com/cztomczak/cef2go/include/capi/cef_app_capi.h:45,
                 from src/cef/cef.go:27:
/home/frederic/go/src/github.com/cztomczak/cef2go/include/internal/cef_types_linux.h:38:21: fatal error: gtk/gtk.h: No such file or directory
 #include <gtk/gtk.h>
                     ^
compilation terminated.
Makefile:33 : la recette pour la cible « Linux » a échouée
make[1]: *** [Linux] Erreur 2
make[1] : on quitte le répertoire « /home/frederic/go/src/github.com/cztomczak/cef2go »
Makefile:30 : la recette pour la cible « detect_os » a échouée
make: *** [detect_os] Erreur 2
```

Development libraries are installed, i checked the needings with:
```
pkg-config --libs --cflags gtk+-2.0
```
The output is:
```
-pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/freetype2 -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype
```

I used latest CEF binaries ([cef_binary_3.3163.1670.g934eaba_linux64.tar.bz2](http://opensource.spotify.com/cefbuilds/cef_binary_3.3163.1670.g934eaba_linux64.tar.bz2))

**Comment by cztomczak** [comment]
Please ask question on the Forum. Latest CEF is not supported.

**Comment by NyxCode** [comment]
Same issue here. I used the cef build linked in the readme (`cef_binary_notcmalloc_3.1750.1604_linux64`)
```
go install gtk
# gtk
src/gtk/gtk.go: In function ‘TerminationSignal’:
src/gtk/gtk.go:14:39: warning: implicit declaration of function ‘cef_quit_message_loop’ [-Wimplicit-function-declaration]
   14 | void TerminationSignal(int signatl) { cef_quit_message_loop(); }
      |                                       ^~~~~~~~~~~~~~~~~~~~~
src/gtk/gtk.go: In function ‘DestroySignal’:
src/gtk/gtk.go:20:5: warning: implicit declaration of function ‘_GoDestroySignal’; did you mean ‘DestroySignal’? [-Wimplicit-function-declaration]
   20 |     _GoDestroySignal(widget, data);
      |     ^~~~~~~~~~~~~~~~
      |     DestroySignal
go install cef
# cef
In file included from /home/moritz/aleph-alpha/cef2go/include/internal/cef_types.h:46,
                 from /home/moritz/aleph-alpha/cef2go/include/capi/cef_base_capi.h:43,
                 from /home/moritz/aleph-alpha/cef2go/include/capi/cef_app_capi.h:45,
                 from src/cef/cef.go:27:
/home/moritz/aleph-alpha/cef2go/include/internal/cef_types_linux.h:38:10: fatal error: gtk/gtk.h: No such file or directory
   38 | #include <gtk/gtk.h>
      |          ^~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:35: Linux] Error 2
make[1]: Leaving directory '/home/moritz/aleph-alpha/cef2go'
make: *** [Makefile:30: detect_os] Error 2
```

`$ pkg-config --libs --cflags gtk+-2.0
-I/usr/include/gtk-2.0 -I/usr/lib/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib/libffi-3.2.1/include -I/usr/include/harfbuzz -I/usr/include/fribidi -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/uuid -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/atk-1.0 -pthread -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lharfbuzz -lfontconfig -lfreetype 
`
